sudo: false

language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly
    include:
        - php: hhvm
          dist: trusty
        - php: 7.1
          env: DEPENDENCIES=lowest

before_install:
    - pip install --user codecov

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction
    - if [ "$DEPENDENCIES" = "lowest" ]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction; fi;

script:
    - make travis

after_success:
    - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then codecov; fi

cache:
    directories:
        - $HOME/.composer/cache
