sudo: false

language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly
    include:
        - php: hhvm
          dist: trusty
        - php: 7.1
          env: DEPENDENCIES=lowest

before_install:
    - pip install --user codecov

before_script:
    - if [[ $TRAVIS_PHP_VERSION == "5.5" ]]; then composer remove --dev equip/dispatch; fi
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction
    - if [ "$DEPENDENCIES" = "lowest" ]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction; fi;

script:
    - vendor/bin/phpcs --standard=psr2 ./src
    - vendor/bin/phpunit --coverage-text --bootstrap vendor/autoload.php --coverage-clover=coverage.xml

after_success:
    - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then codecov; fi

cache:
    directories:
        - $HOME/.composer/cache
